package Fornecedor;

import DAO.FornecedorDAO;
import DAO.FornecedorDAO;
import Menu.Menu;
import Models.Fornecedor;
import Models.Fornecedor;
import javax.swing.JOptionPane;

/**
 *
 * @author 2830482411045
 */
public class CadastroFornecedor extends javax.swing.JFrame {

    /**
     * Creates new form Cadastrofornecedor
     */
    public CadastroFornecedor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_Titulo = new javax.swing.JLabel();
        btn_Menu = new javax.swing.JButton();
        lbl_Nome = new javax.swing.JLabel();
        lbl_Rua = new javax.swing.JLabel();
        lbl_Bairro = new javax.swing.JLabel();
        lbl_Cidade = new javax.swing.JLabel();
        lbl_CEP = new javax.swing.JLabel();
        lbl_UF = new javax.swing.JLabel();
        lbl_Email = new javax.swing.JLabel();
        lbl_Telefone = new javax.swing.JLabel();
        txt_Nome = new javax.swing.JTextField();
        txt_Rua = new javax.swing.JTextField();
        txt_Bairro = new javax.swing.JTextField();
        txt_Cidade = new javax.swing.JTextField();
        txt_CEP = new javax.swing.JTextField();
        txt_UF = new javax.swing.JTextField();
        txt_Email = new javax.swing.JTextField();
        txt_Telefone = new javax.swing.JTextField();
        lbl_Codigo = new javax.swing.JLabel();
        txt_FornecedorID = new javax.swing.JTextField();
        lbl_ConsultaID = new javax.swing.JLabel();
        txt_ID = new javax.swing.JTextField();
        btn_Consultar = new javax.swing.JButton();
        btn_Cadastrar = new javax.swing.JButton();
        btn_Atualizar = new javax.swing.JButton();
        btn_Deletar = new javax.swing.JButton();
        txt_Numero = new javax.swing.JTextField();
        lbl_Numero = new javax.swing.JLabel();
        btn_ListaFornecedor = new javax.swing.JButton();
        txt_NomeFantasia = new javax.swing.JTextField();
        lbl_NomeFantasia = new javax.swing.JLabel();
        lbl_CNPJ = new javax.swing.JLabel();
        txt_CNPJ = new javax.swing.JTextField();
        btn_Limpar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbl_Titulo.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        lbl_Titulo.setText("Gerenciar Fornecedor");

        btn_Menu.setText("Voltar");
        btn_Menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_MenuActionPerformed(evt);
            }
        });

        lbl_Nome.setText("Nome: ");

        lbl_Rua.setText("Rua:");

        lbl_Bairro.setText("Bairro:");

        lbl_Cidade.setText("Cidade:");

        lbl_CEP.setText("CEP:");

        lbl_UF.setText("UF:");

        lbl_Email.setText("Email:");

        lbl_Telefone.setText("Telefone:");

        lbl_Codigo.setText("Código:");

        txt_FornecedorID.setEnabled(false);

        lbl_ConsultaID.setText("Consulta Código:");

        btn_Consultar.setText("Consultar");
        btn_Consultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ConsultarActionPerformed(evt);
            }
        });

        btn_Cadastrar.setText("Cadastrar");
        btn_Cadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CadastrarActionPerformed(evt);
            }
        });

        btn_Atualizar.setText("Atualizar");
        btn_Atualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_AtualizarActionPerformed(evt);
            }
        });

        btn_Deletar.setText("Deletar");
        btn_Deletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_DeletarActionPerformed(evt);
            }
        });

        lbl_Numero.setText("nº:");

        btn_ListaFornecedor.setText("Lista de Fornecedor");
        btn_ListaFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ListaFornecedorActionPerformed(evt);
            }
        });

        lbl_NomeFantasia.setText("Nome Fan.");

        lbl_CNPJ.setText("CNPJ");

        btn_Limpar.setText("Limpar");
        btn_Limpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_LimparActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn_Menu)
                        .addGap(377, 377, 377)
                        .addComponent(btn_ListaFornecedor))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lbl_NomeFantasia)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_Consultar, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbl_Codigo)
                                .addGap(18, 18, 18)
                                .addComponent(txt_FornecedorID, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lbl_Email)
                            .addComponent(lbl_CNPJ)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(lbl_Telefone)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txt_Telefone, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(lbl_Cidade)
                                                        .addComponent(lbl_CEP))
                                                    .addGap(18, 18, 18))
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(lbl_Bairro)
                                                    .addGap(24, 24, 24)))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(lbl_Rua)
                                                .addGap(35, 35, 35)))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txt_Bairro)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(txt_CEP, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(lbl_UF)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(txt_UF, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(txt_Cidade)
                                            .addComponent(txt_Email)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(txt_Rua)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(lbl_Numero)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(txt_Numero, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(txt_CNPJ, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(txt_NomeFantasia, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(34, 34, 34)
                                    .addComponent(btn_Deletar)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btn_Atualizar)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btn_Limpar)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btn_Cadastrar)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lbl_Titulo)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lbl_Nome)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(58, 58, 58)
                                                .addComponent(txt_Nome, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(40, 40, 40)
                                        .addComponent(lbl_ConsultaID)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_ID, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_Titulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_FornecedorID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_Codigo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_Nome)
                    .addComponent(txt_Nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_ConsultaID)
                    .addComponent(txt_ID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_NomeFantasia)
                    .addComponent(txt_NomeFantasia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Consultar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_CNPJ)
                    .addComponent(txt_CNPJ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_Rua)
                            .addComponent(txt_Rua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_Bairro)
                            .addComponent(txt_Bairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_Cidade)
                            .addComponent(txt_Cidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_CEP)
                            .addComponent(txt_CEP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_UF)
                            .addComponent(txt_UF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_Email)
                            .addComponent(txt_Email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_Telefone)
                            .addComponent(txt_Telefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lbl_Numero)
                        .addComponent(txt_Numero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_Cadastrar)
                    .addComponent(btn_Limpar)
                    .addComponent(btn_Atualizar)
                    .addComponent(btn_Deletar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_ListaFornecedor)
                    .addComponent(btn_Menu))
                .addGap(12, 12, 12))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_MenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_MenuActionPerformed
        Menu menu = new Menu(); // Cria uma nova instância do formulário
        menu.setVisible(true); //abri o forms
        dispose(); //fecha a tela em background
    }//GEN-LAST:event_btn_MenuActionPerformed

    private void btn_CadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CadastrarActionPerformed
        Fornecedor fornecedor = new Fornecedor();
        fornecedor.setNome(txt_Nome.getText());
        fornecedor.setNomeFantasia(txt_NomeFantasia.getText());
        fornecedor.setCnpj(txt_CNPJ.getText());
        fornecedor.setRua(txt_Rua.getText());
        fornecedor.setBairro(txt_Bairro.getText());
        fornecedor.setNumero(txt_Numero.getText());
        fornecedor.setCidade(txt_Cidade.getText());
        fornecedor.setCEP(txt_CEP.getText());
        fornecedor.setUF(txt_UF.getText());
        fornecedor.setEmail(txt_Email.getText());
        fornecedor.setTelefone(txt_Telefone.getText());

        FornecedorDAO fDAO = new FornecedorDAO();
        fDAO.inserirFornecedor(fornecedor);

        limparFormulario();
    }//GEN-LAST:event_btn_CadastrarActionPerformed

    private void btn_AtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_AtualizarActionPerformed
        Fornecedor fornecedor = new Fornecedor();
        fornecedor.setID(Integer.parseInt(txt_FornecedorID.getText()));
        fornecedor.setNome(txt_Nome.getText());
        fornecedor.setNomeFantasia(txt_NomeFantasia.getText());
        fornecedor.setCnpj(txt_CNPJ.getText());
        fornecedor.setRua(txt_Rua.getText());
        fornecedor.setBairro(txt_Bairro.getText());
        fornecedor.setNumero(txt_Numero.getText());
        fornecedor.setCidade(txt_Cidade.getText());
        fornecedor.setCEP(txt_CEP.getText());
        fornecedor.setUF(txt_UF.getText());
        fornecedor.setEmail(txt_Email.getText());
        fornecedor.setTelefone(txt_Telefone.getText());

        FornecedorDAO fDAO = new FornecedorDAO();
        fDAO.editarFornecedor(fornecedor);
        limparFormulario();
    }//GEN-LAST:event_btn_AtualizarActionPerformed

    private void btn_ConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ConsultarActionPerformed
        int idFornecedor = Integer.parseInt(txt_ID.getText());
        FornecedorDAO fDAO = new FornecedorDAO();

        Fornecedor fornecedor = fDAO.getFornecedor(idFornecedor);
        if (fornecedor == null) {
            limparFormulario();
            JOptionPane.showMessageDialog(this, "Fornecedor  não encontrada!");
        } else {
            txt_ID.setText(String.valueOf(fornecedor.getID()));
            txt_FornecedorID.setText(String.valueOf(fornecedor.getID()));
            txt_Nome.setText(String.valueOf(fornecedor.getNome()));
            txt_NomeFantasia.setText(String.valueOf(fornecedor.getNomeFantasia()));
            txt_CNPJ.setText(String.valueOf(fornecedor.getCnpj()));
            txt_Rua.setText(String.valueOf(fornecedor.getRua()));
            txt_Numero.setText(String.valueOf(fornecedor.getNumero()));
            txt_Bairro.setText(String.valueOf(fornecedor.getBairro()));
            txt_Cidade.setText(String.valueOf(fornecedor.getCidade()));
            txt_CEP.setText(String.valueOf(fornecedor.getCEP()));
            txt_UF.setText(String.valueOf(fornecedor.getUF()));
            txt_Email.setText(String.valueOf(fornecedor.getEmail()));
            txt_Telefone.setText(String.valueOf(fornecedor.getTelefone()));
        }
    }//GEN-LAST:event_btn_ConsultarActionPerformed

    private void btn_DeletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_DeletarActionPerformed
        int resposta = JOptionPane.showConfirmDialog(null, "Deseja realmente excluir este Fornecedor?",
                "Exclusão", JOptionPane.YES_NO_OPTION);

        if (resposta == JOptionPane.YES_OPTION) {
            FornecedorDAO fDAO = new FornecedorDAO();
            fDAO.excluirFornecedor(Integer.parseInt(txt_ID.getText()));
            limparFormulario();
        }
    }//GEN-LAST:event_btn_DeletarActionPerformed

    private void btn_ListaFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ListaFornecedorActionPerformed
        FornecedorList fn = new FornecedorList();
        fn.setVisible(true); //abri o forms
        dispose(); //fecha a tela em background
    }//GEN-LAST:event_btn_ListaFornecedorActionPerformed

    private void btn_LimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_LimparActionPerformed
        limparFormulario();
    }//GEN-LAST:event_btn_LimparActionPerformed

    private void limparFormulario() {
        txt_Nome.setText("");
        txt_NomeFantasia.setText("");
        txt_CNPJ.setText("");
        txt_Rua.setText("");
        txt_Bairro.setText("");
        txt_Numero.setText("");
        txt_Cidade.setText("");
        txt_CEP.setText("");
        txt_UF.setText("");
        txt_Email.setText("");
        txt_Telefone.setText("");
        txt_ID.setText("");
        txt_FornecedorID.setText("");
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroFornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroFornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroFornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroFornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroFornecedor().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Atualizar;
    private javax.swing.JButton btn_Cadastrar;
    private javax.swing.JButton btn_Consultar;
    private javax.swing.JButton btn_Deletar;
    private javax.swing.JButton btn_Limpar;
    private javax.swing.JButton btn_ListaFornecedor;
    private javax.swing.JButton btn_Menu;
    private javax.swing.JLabel lbl_Bairro;
    private javax.swing.JLabel lbl_CEP;
    private javax.swing.JLabel lbl_CNPJ;
    private javax.swing.JLabel lbl_Cidade;
    private javax.swing.JLabel lbl_Codigo;
    private javax.swing.JLabel lbl_ConsultaID;
    private javax.swing.JLabel lbl_Email;
    private javax.swing.JLabel lbl_Nome;
    private javax.swing.JLabel lbl_NomeFantasia;
    private javax.swing.JLabel lbl_Numero;
    private javax.swing.JLabel lbl_Rua;
    private javax.swing.JLabel lbl_Telefone;
    private javax.swing.JLabel lbl_Titulo;
    private javax.swing.JLabel lbl_UF;
    private javax.swing.JTextField txt_Bairro;
    private javax.swing.JTextField txt_CEP;
    private javax.swing.JTextField txt_CNPJ;
    private javax.swing.JTextField txt_Cidade;
    private javax.swing.JTextField txt_Email;
    private javax.swing.JTextField txt_FornecedorID;
    private javax.swing.JTextField txt_ID;
    private javax.swing.JTextField txt_Nome;
    private javax.swing.JTextField txt_NomeFantasia;
    private javax.swing.JTextField txt_Numero;
    private javax.swing.JTextField txt_Rua;
    private javax.swing.JTextField txt_Telefone;
    private javax.swing.JTextField txt_UF;
    // End of variables declaration//GEN-END:variables
}
